### ISSUE TITLE
Clean up readme file

### ISSUE THREAD

**Issue by ccrow42** [PureStorage-OpenConnect/TestDriveNewStack#5]
needs to be clarified so that a non-linux admin can run through the demo.

Document the script for kubernetes steps.

**Comment by sdodsley** [comment]
Can you also remove all references to PSO and Kubernetes from the README.

I saw the big section at the end was removed, but there are references elsewhere

**Comment by kbkuebler** [comment]
All refs to PSO should be gone now. Thanks!
